package org.swinglife.common.entity.dao;

import java.util.List;
import org.swinglife.common.entity.Message;
import org.swinglife.common.entity.MessageExample;

public interface MessageDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    void insert(Message record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    int updateByPrimaryKey(Message record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    List selectByExample(MessageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    Message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    int countByExample(MessageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    int updateByExampleSelective(Message record, MessageExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    int updateByExample(Message record, MessageExample example);
}