package org.swinglife.common.entity.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;
import org.swinglife.common.dao.BaseDao;
import org.swinglife.common.entity.Message;
import org.swinglife.common.entity.MessageExample;

@Repository
public class MessageDAOImpl extends BaseDao implements MessageDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public MessageDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public void insert(Message record) {
        getSqlMapClientTemplate().insert("message.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public int updateByPrimaryKey(Message record) {
        int rows = getSqlMapClientTemplate().update("message.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public int updateByPrimaryKeySelective(Message record) {
        int rows = getSqlMapClientTemplate().update("message.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public List selectByExample(MessageExample example) {
        List list = getSqlMapClientTemplate().queryForList("message.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public Message selectByPrimaryKey(Integer id) {
        Message key = new Message();
        key.setId(id);
        Message record = (Message) getSqlMapClientTemplate().queryForObject("message.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public int deleteByExample(MessageExample example) {
        int rows = getSqlMapClientTemplate().delete("message.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        Message key = new Message();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("message.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public int countByExample(MessageExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("message.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public int updateByExampleSelective(Message record, MessageExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("message.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public int updateByExample(Message record, MessageExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("message.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table message
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    private static class UpdateByExampleParms extends MessageExample {
        private Object record;

        public UpdateByExampleParms(Object record, MessageExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}