package org.swinglife.common.entity.dao;

import java.util.List;
import org.swinglife.common.entity.Persons;
import org.swinglife.common.entity.PersonsExample;

public interface PersonsDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    void insert(Persons record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    List selectByExample(PersonsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    int deleteByExample(PersonsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    int countByExample(PersonsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    int updateByExampleSelective(Persons record, PersonsExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    int updateByExample(Persons record, PersonsExample example);
}