package org.swinglife.common.entity.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.swinglife.common.entity.Persons;
import org.swinglife.common.entity.PersonsExample;

public class PersonsDAOImpl extends SqlMapClientDaoSupport implements PersonsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public PersonsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public void insert(Persons record) {
        getSqlMapClientTemplate().insert("persons.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public List selectByExample(PersonsExample example) {
        List list = getSqlMapClientTemplate().queryForList("persons.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public int deleteByExample(PersonsExample example) {
        int rows = getSqlMapClientTemplate().delete("persons.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public int countByExample(PersonsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("persons.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public int updateByExampleSelective(Persons record, PersonsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("persons.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public int updateByExample(Persons record, PersonsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("persons.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table persons
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    private static class UpdateByExampleParms extends PersonsExample {
        private Object record;

        public UpdateByExampleParms(Object record, PersonsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}