package org.swinglife.common.entity;

public class Message {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column message.ID
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column message.COMMAND
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    private String command;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column message.DESCRIPTION
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column message.CONTENT
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    private String content;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column message.ID
     *
     * @return the value of message.ID
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column message.ID
     *
     * @param id the value for message.ID
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column message.COMMAND
     *
     * @return the value of message.COMMAND
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column message.COMMAND
     *
     * @param command the value for message.COMMAND
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public void setCommand(String command) {
        this.command = command == null ? null : command.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column message.DESCRIPTION
     *
     * @return the value of message.DESCRIPTION
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column message.DESCRIPTION
     *
     * @param description the value for message.DESCRIPTION
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column message.CONTENT
     *
     * @return the value of message.CONTENT
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column message.CONTENT
     *
     * @param content the value for message.CONTENT
     *
     * @abatorgenerated Tue Apr 05 11:15:55 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}