package org.swinglife.common.entity;



public class Persons {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column persons.Id_P
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    private Integer idP;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column persons.LastName
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    private String lastname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column persons.FirstName
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    private String firstname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column persons.Address
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column persons.City
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    private String city;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column persons.Id_P
     *
     * @return the value of persons.Id_P
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public Integer getIdP() {
        return idP;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column persons.Id_P
     *
     * @param idP the value for persons.Id_P
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public void setIdP(Integer idP) {
        this.idP = idP;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column persons.LastName
     *
     * @return the value of persons.LastName
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column persons.LastName
     *
     * @param lastname the value for persons.LastName
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column persons.FirstName
     *
     * @return the value of persons.FirstName
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column persons.FirstName
     *
     * @param firstname the value for persons.FirstName
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column persons.Address
     *
     * @return the value of persons.Address
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column persons.Address
     *
     * @param address the value for persons.Address
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column persons.City
     *
     * @return the value of persons.City
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column persons.City
     *
     * @param city the value for persons.City
     *
     * @abatorgenerated Sat Sep 20 22:56:53 CST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}